#!/bin/bash

# Quick start Railway deployment
# This script pushes your code and shows what to do in Railway dashboard

set -e

echo "════════════════════════════════════════════════════════"
echo "   BodaLoan Deployment - Final Steps"
echo "════════════════════════════════════════════════════════"
echo ""

# Step 1: Commit and push
echo "📤 Checking git status..."
if [ -z "$(git status --porcelain)" ]; then
    echo "✓ Working directory already clean"
else
    echo "📝 Committing changes..."
    git add .
    git commit -m "Final deployment configuration for Railway" || echo "✓ No new changes to commit"
fi

echo "🚀 Pushing to GitHub..."
git push origin main || {
    echo "⚠️  Push failed - you might need to pull first"
    echo "   Try: git pull origin main"
    exit 1
}

echo ""
echo "════════════════════════════════════════════════════════"
echo "✅ Code pushed to GitHub successfully!"
echo ""
echo "🎯 YOUR NEXT STEPS:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Open https://railway.app/dashboard"
echo ""
echo "2️⃣  Click on 'BODALOAN' project"
echo ""
echo "3️⃣  Make sure these services are connected:"
echo "    ✓ Web Service (from GitHub repo)"
echo "    ✓ PostgreSQL Database"
echo ""
echo "4️⃣  Click 'Variables' tab and set THESE critical variables:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "COPY FROM .env file:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
grep "APP_KEY=" .env && grep "APP_KEY=" .env | sed 's/^/   /' || echo "   APP_KEY=base64:YOUR_KEY_HERE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SET THESE EXACT VALUES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   APP_NAME=BodaLoan"
echo "   APP_ENV=production"
echo "   APP_DEBUG=false"
echo "   APP_TIMEZONE=Africa/Dar_es_Salaam"
echo "   APP_URL=https://bodaloan-production.up.railway.app"
echo ""
echo "   DB_CONNECTION=pgsql"
echo "   DB_HOST=\${{PGHOST}}"
echo "   DB_PORT=\${{PGPORT}}"
echo "   DB_DATABASE=\${{PGDATABASE}}"
echo "   DB_USERNAME=\${{PGUSER}}"
echo "   DB_PASSWORD=\${{PGPASSWORD}}"
echo ""
echo "   LOG_LEVEL=notice"
echo "   SESSION_DRIVER=file"
echo "   CACHE_STORE=file"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "COPY FIREBASE & SERVICES FROM .env:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
grep "FIREBASE_" .env | sed 's/^/   /' || echo "   [Check your .env file]"
echo ""
echo "5️⃣  Click 'Deploy' button (or wait for auto-deploy)"
echo ""
echo "6️⃣  Watch the logs - should show:"
echo ""
echo "   ✓ Checking environment variables..."
echo "   ✓ Creating storage directories..."
echo "   ✓ Caching configuration..."
echo "   ✓ Running database migrations..."
echo "   ✓ Deployment setup completed successfully!"
echo ""
echo "7️⃣  Click the URL in Railway dashboard"
echo ""
echo "8️⃣  You should see the BodaLoan login page (NOT 500 error!)"
echo ""
echo "════════════════════════════════════════════════════════"
echo "❓ STILL GETTING 500 ERROR?"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Check these in Railway Logs:"
echo ""
echo "1. Missing APP_KEY?"
echo "   → Set APP_KEY variable in Railway Variables tab"
echo ""
echo "2. Database error?"
echo "   → Make sure PostgreSQL service is connected"
echo "   → Verify DB_* variables are set"
echo ""
echo "3. PHP error?"
echo "   → Look for error message in logs"
echo "   → Most common: missing environment variables"
echo ""
echo "📖 Full guide: see DEPLOYMENT.md in repo"
echo ""
echo "════════════════════════════════════════════════════════"
